databases:
  - name: ocha_app_db_dev
    databaseName: ochadb-dev
    user: shimekake
    region: singapore

services:
  - type: web
    name: ocha_app_dev
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: ocha_app_db_dev
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
